seed: 42
device: cuda
amp: true

data:
  train_data_dir: data/train
  val_data_dir: data/val

model:
  in_channels: 1
  out_channels: 2
  patch_size: [64, 64, 64]
  spacing: null

train:
  epochs: 20
  batch_size: 1
  lr: 1.0e-3
  weight_decay: 1.0e-4
  num_workers: 4
  loss: tversky
  fbeta: 4.0